NIDAIntegration/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NIDAIntegration.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

NIDAIntegration/Controllers/SamlController.cs
using System.IO;
using System.Security.Cryptography.X509Certificates;
using System.Web;
using System.Web.Mvc;
using Nida.Saml.ServiceProvider;
using Nida.Constants;
using NIDAIntegration.Properties;
using NidaIntegration.Saml;
using NIDAIntegration.Constants;
using System.Collections.Generic;
using NIDAIntegration.Models;
using System;
using NIDAIntegration.CISService;
using NIDAIntegration.Helpers;

namespace NIDAIntegration.Controllers
{
    public class SamlController : Controller
    {
        private RelayModel _relayModel;

        public SamlController()
        {

            _relayModel = new RelayModel
            {
                SasKeyName = ConfigurationHelper.SasKeyName,
                ServiceNamespace = ConfigurationHelper.ServiceNamespace,
                SasKey = ConfigurationHelper.SasKey,
                Method = "OnlineUser"
            };
        }
        public ActionResult AssertionConsumerService()
        {
            // Load Idp public certificate
            var identityProviderX509Certificate = (X509Certificate2)((WebApiApplication)HttpContext.ApplicationInstance).Application[NIDAIntegrationConstants.IdPx509Certificate];

            // Load Sp certificate + private key
            //var fileName = Path.Combine(HttpRuntime.AppDomainAppPath, Settings.Default.SpCertificateFileName);
            var fileName = HttpContext.Server.MapPath(String.Format("~/App_Data/{0}", Settings.Default.SpCertificateFileName));
            var serviceProviderX509Certificate = new X509Certificate2(fileName, Settings.Default.SpPassword);

            // set up out variables
            string persistentId;
            int levelOfAssurance;
            bool levelOfAssurancePending;
            bool success;
            string message;
            string inResponseToSamlRequestId;

            var samlAssertionReceiver = new SamlAssertionReceiver(identityProviderX509Certificate, serviceProviderX509Certificate);
            samlAssertionReceiver.ProcessSamlResponse(out persistentId, out inResponseToSamlRequestId, out levelOfAssurance, out levelOfAssurancePending, out success, out message);

            //var cisService = new CISServiceClient();

            //Guid persistentGuid;
            //if (!Guid.TryParse(persistentId, out persistentGuid))
            //{
            //    // error with Parsing Saml
            //}

            //var onlineUser = cisService.GetOnlineUser(persistentGuid);

            var model = new SamlResponseViewModel
            {
                PersistentId = persistentId,
                InResponseToSamlRequestId = inResponseToSamlRequestId,
                LevelOfAssurance = levelOfAssurance,
                LevelOfAssurancePending = levelOfAssurancePending,
                Success = success,
                Message = message,
                OnlineUser = new OnlineUser()
            };

            return View(model);
        }

        public ActionResult SendSamlRequest(int levelOfAssurance, string persistentId = "")
        {
            var serviceProviderX509Certificate2 = (X509Certificate2)((WebApiApplication)HttpContext.ApplicationInstance).Application[NIDAIntegrationConstants.Spx509Certificate];
            var identityProviderX509Certificate2 = (X509Certificate2)((WebApiApplication)HttpContext.ApplicationInstance).Application[NIDAIntegrationConstants.IdPx509Certificate];
            string samlRequestId;

            var samlSender = new SamlRequestSender(Settings.Default.ServiceProviderUrl, Settings.Default.IdentityProviderRequestConsumerUrl, serviceProviderX509Certificate2, identityProviderX509Certificate2);
            samlSender.SendAuthenticationRequest(levelOfAssurance, out samlRequestId, persistentId);

            System.Web.HttpContext.Current.Response.End();
            return null;
        }

        public ActionResult MatchRequests()
        {
            var filenames = Directory.EnumerateFiles(Settings.Default.MatchRequestsFolder);

            var jsonModel = new JSONModel { MatchRequests = new List<string>() };
            foreach (var filename in filenames)
            {
                jsonModel.MatchRequests.Add(System.IO.File.ReadAllText(filename));

            }

            return View(jsonModel);
        }
    }
}

NIDAIntegration/Views/Home/Index.cshtml
@{
    ViewBag.Title = "NICS Test Harness";
}

<h1 id="skip-dest">Test Harness Home Page</h1>

<p class="intro">
    This is the home page of the Service Provider Test Harness
</p>
<p>
    @Html.ActionLink("Request LOA 1", "SendSamlRequest", "Saml", new { levelOfAssurance = 1 }, new { @class = "btn btn-call-to-action" })

    @Html.ActionLink("Request LOA 2", "SendSamlRequest", "Saml", new { levelOfAssurance = 2 }, new { @class = "btn btn-call-to-action" })

    @Html.ActionLink("Request LOA 3", "SendSamlRequest", "Saml", new { levelOfAssurance = 3 }, new { @class = "btn btn-call-to-action" })

    <a href="@NIDAIntegration.Helpers.SettingsHelper.GetAccountManagementUrl()" class="btn btn-call-to-action">nidirect account management</a>
</p>
<hr />
<div class="form-horizontal">
    <div class="control-group">
        <label>Enter PersistentId for the simulated functions below</label>
        <input type="text" id="persistentIdTextBox" />
    </div>
</div>
<br />
@Html.ActionLink("Request LOA-2", "SendSamlRequest", "Saml", new { levelOfAssurance = 2, persistentId = "fakePersistentId" }, new { @class = "btn btn-call-to-action", @id = "Loa1UserLoggedInAsLoa1RequestsLoa2Service" })

@section scripts
{
<script type="text/javascript">
        $(function () {
            $("#Loa1UserLoggedInAsLoa1RequestsLoa2Service").click(function () {
                var fakedUri = $("#Loa1UserLoggedInAsLoa1RequestsLoa2Service").prop("href");
                var uri = fakedUri.replace("fakePersistentId", $("#persistentIdTextBox").val());
                $("#Loa1UserLoggedInAsLoa1RequestsLoa2Service").prop("href", uri);
            });
        });
</script>
}